//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bininator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxHead_Value {
            get {
                return ((string)(this["maskedTextBoxHead_Value"]));
            }
            set {
                this["maskedTextBoxHead_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxElastic_Value {
            get {
                return ((string)(this["maskedTextBoxElastic_Value"]));
            }
            set {
                this["maskedTextBoxElastic_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxLoop_Value {
            get {
                return ((string)(this["maskedTextBoxLoop_Value"]));
            }
            set {
                this["maskedTextBoxLoop_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxRow_Value {
            get {
                return ((string)(this["maskedTextBoxRow_Value"]));
            }
            set {
                this["maskedTextBoxRow_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxBeforeWtoLoop_Value {
            get {
                return ((string)(this["maskedTextBoxBeforeWtoLoop_Value"]));
            }
            set {
                this["maskedTextBoxBeforeWtoLoop_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxBeforeWtoRow_Value {
            get {
                return ((string)(this["maskedTextBoxBeforeWtoRow_Value"]));
            }
            set {
                this["maskedTextBoxBeforeWtoRow_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxAfterWtoRow_Value {
            get {
                return ((string)(this["maskedTextBoxAfterWtoRow_Value"]));
            }
            set {
                this["maskedTextBoxAfterWtoRow_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string maskedTextBoxAfterWtoLoop_Value {
            get {
                return ((string)(this["maskedTextBoxAfterWtoLoop_Value"]));
            }
            set {
                this["maskedTextBoxAfterWtoLoop_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int checkedRB {
            get {
                return ((int)(this["checkedRB"]));
            }
            set {
                this["checkedRB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxBini {
            get {
                return ((bool)(this["checkBoxBini"]));
            }
            set {
                this["checkBoxBini"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool checkBoxElastik {
            get {
                return ((bool)(this["checkBoxElastik"]));
            }
            set {
                this["checkBoxElastik"] = value;
            }
        }
    }
}
